project = 'Basalt2'
title = 'Basalt2 Documentation'
description = 'A powerful UI Framework for ComputerCraft'
format = 'markdown'
dir = 'docs'
file = {'src'}
style = '!pale'
sort = true
not_luadoc = true
all = true
no_space_before_args = true
wrap = true
one = true  -- Generiere eine Datei pro Modul
recurse = true  -- Rekursiv durch Unterverzeichnisse gehen
shallow = true  -- Behalte Verzeichnisstruktur bei
kind_names = {module = 'Modules', topic = 'Topics'}
